GET http://localhost:3000/users

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Kent",
    "password": "cats"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "Walt",
    "password": "dogs"
}

###
GET http://localhost:3000/query